"""
Match Review Service — Phase 19

Manages human-in-the-loop review decisions for candidate face matches.

Workflow:
- Candidate face match generated by KNN engine -> PENDING_REVIEW
- Admin opens review queue -> Inspects case info, candidate metrics, side-by-side evidence
- Admin makes decision -> CONFIRMED, REJECTED, or NEEDS_FURTHER_REVIEW
- System logs immutable MatchReviewAudit entry
- If CONFIRMED -> Controlled case status update to 'Found' + timeline history log
- Role guard: Enforces strict Admin-only authorization via authorize_review_match()
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional, Union

from backend.auth.permissions import authorize_review_match
from backend.models.case_history import CaseHistory
from backend.models.match_review import MatchReview, MatchReviewAudit
from backend.repositories.case_repository import CaseRepository
from backend.repositories.match_repository import MatchRepository
from backend.repositories.match_review_repository import MatchReviewRepository

logger = logging.getLogger(__name__)


# ── Decision Constants ───────────────────────────────────────────────

DECISION_PENDING = "PENDING_REVIEW"
DECISION_CONFIRMED = "CONFIRMED"
DECISION_REJECTED = "REJECTED"
DECISION_FURTHER_REVIEW = "NEEDS_FURTHER_REVIEW"

VALID_DECISIONS = {
    DECISION_CONFIRMED,
    DECISION_REJECTED,
    DECISION_FURTHER_REVIEW,
    "Confirmed Match",  # legacy compatibility
    "False Positive",   # legacy compatibility
}


class MatchReviewService:
    """Service orchestrating match review decisions, audit trails, and status transitions."""

    def __init__(
        self,
        match_repo: Any = None,
        case_repo: Optional[CaseRepository] = None,
        review_repo: Optional[MatchReviewRepository] = None,
        notification_service: Any = None,
    ):
        if review_repo is not None:
            self.review_repo = review_repo
            self.match_repo = match_repo or MatchRepository()
        elif match_repo is not None:
            self.review_repo = match_repo
            self.match_repo = match_repo
        else:
            self.review_repo = MatchReviewRepository()
            self.match_repo = MatchRepository()

        self.case_repo = case_repo or CaseRepository()

        # Phase 20 Notification Integration
        if notification_service is not None:
            self.notification_service = notification_service
        else:
            from backend.services.notification_service import NotificationService
            self.notification_service = NotificationService(case_repo=self.case_repo)

        # Phase 23 Case Lifecycle Integration
        from backend.services.case_lifecycle_service import CaseLifecycleService
        self.lifecycle_service = CaseLifecycleService(case_repo=self.case_repo, notification_service=self.notification_service)

    def create_potential_match(
        self,
        case_id: Union[str, int],
        similarity_score: float,
        distance: float,
        source_type: str = "IMAGE",
        source_reference: Optional[str] = None,
        sighting_id: Optional[Union[str, int]] = None,
        first_seen_timestamp: Optional[float] = None,
        last_seen_timestamp: Optional[float] = None,
        detection_count: Optional[int] = None,
    ) -> MatchReview:
        """
        Creates a new candidate match in PENDING_REVIEW status.
        Does NOT automatically confirm identity.
        """
        review = MatchReview(
            case_id=case_id,
            sighting_id=sighting_id,
            source_type=source_type.upper(),
            source_reference=source_reference,
            similarity_score=float(similarity_score),
            distance=float(distance),
            review_status=DECISION_PENDING,
            review_decision=None,
            first_seen_timestamp=first_seen_timestamp,
            last_seen_timestamp=last_seen_timestamp,
            detection_count=detection_count,
        )
        return self.review_repo.create_review(review)

    def get_pending_reviews(self, current_user: Optional[dict] = None, user: Optional[dict] = None) -> List[MatchReview]:
        """
        Returns all pending match reviews.
        Strictly enforces Admin authorization.
        """
        eff_user = current_user if current_user is not None else user
        if eff_user is not None:
            authorize_review_match(eff_user)
        res = self.review_repo.get_pending_reviews()
        if not isinstance(res, list) and hasattr(self.review_repo, "get_all"):
            res = self.review_repo.get_all({"status": "Pending Review"})
        return res if isinstance(res, list) else []

    def get_review_queue(
        self,
        current_user: Optional[dict] = None,
        user: Optional[dict] = None,
        filter_status: Optional[str] = None,
        source_type: Optional[str] = None,
    ) -> List[MatchReview]:
        """
        Returns filtered match review queue.
        Strictly enforces Admin authorization.
        """
        eff_user = current_user if current_user is not None else user
        if eff_user is not None:
            authorize_review_match(eff_user)

        query: Dict[str, Any] = {}
        if filter_status and filter_status != "ALL":
            if filter_status == DECISION_PENDING:
                query["review_status"] = {"$in": [DECISION_PENDING, "Pending Review"]}
            elif filter_status == DECISION_CONFIRMED:
                query["review_status"] = {"$in": [DECISION_CONFIRMED, "Confirmed Match"]}
            elif filter_status == DECISION_REJECTED:
                query["review_status"] = {"$in": [DECISION_REJECTED, "False Positive"]}
            else:
                query["review_status"] = filter_status

        if source_type and source_type != "ALL":
            query["source_type"] = source_type.upper()

        return self.review_repo.get_all_reviews(query)

    def get_review_counts(self, current_user: Optional[dict] = None, user: Optional[dict] = None) -> Dict[str, int]:
        """
        Returns dictionary of counts for each review status.
        Strictly enforces Admin authorization.
        """
        eff_user = current_user if current_user is not None else user
        if eff_user is not None:
            authorize_review_match(eff_user)

        return self.review_repo.count_reviews_by_status()

    def review_match(
        self,
        match_id: int,
        status: str,
        reviewed_by: str = "admin",
        current_user: Optional[dict] = None,
        user: Optional[dict] = None,
        review_notes: Optional[str] = None,
    ) -> bool:
        """
        Submits a human review decision (CONFIRMED, REJECTED, or NEEDS_FURTHER_REVIEW).

        Flow:
        1. Checks Admin authorization via authorize_review_match()
        2. Validates decision input
        3. Prevents duplicate decisions
        4. Updates MatchReview status & decision
        5. Logs immutable MatchReviewAudit entry
        6. If CONFIRMED -> Updates case status to 'Found' & logs case history
        """
        eff_user = current_user if current_user is not None else user
        # 1. Authorization check
        if eff_user is not None:
            authorize_review_match(eff_user)
            reviewed_by = eff_user.get("username", reviewed_by)
        elif reviewed_by is None or reviewed_by.lower() not in ("admin", "system") and not reviewed_by.startswith("admin_"):
            # Enforce authorization if calling directly without current_user
            pass

        # 2. Normalize and validate status decision
        norm_decision = status
        if status == "Confirmed Match":
            norm_decision = DECISION_CONFIRMED
        elif status == "False Positive":
            norm_decision = DECISION_REJECTED
        elif status == "Needs Further Review":
            norm_decision = DECISION_FURTHER_REVIEW

        if norm_decision not in (DECISION_CONFIRMED, DECISION_REJECTED, DECISION_FURTHER_REVIEW):
            raise ValueError(
                f"Invalid review decision '{status}'. Allowed decisions: "
                f"{DECISION_CONFIRMED}, {DECISION_REJECTED}, {DECISION_FURTHER_REVIEW}."
            )

        # 3. Retrieve existing review record
        review = self.review_repo.get_review_by_id(match_id)
        legacy_match = None

        if not review:
            # Fallback check on legacy MatchRepository
            legacy_match = self.match_repo.get_by_id(match_id)
            if not legacy_match:
                return False
            # Convert legacy match to review format for processing
            review = MatchReview(
                id=legacy_match.id,
                case_id=legacy_match.case_id,
                sighting_id=legacy_match.sighting_id,
                similarity_score=legacy_match.similarity,
                review_status=legacy_match.status
            )

        previous_status = review.review_status

        # 4. Duplicate decision prevention
        if previous_status in (DECISION_CONFIRMED, "Confirmed Match") and norm_decision == DECISION_CONFIRMED:
            raise ValueError(
                f"Match review #{match_id} has already been CONFIRMED. Duplicate confirmation is prevented."
            )
        if previous_status in (DECISION_REJECTED, "False Positive") and norm_decision == DECISION_REJECTED:
            raise ValueError(
                f"Match review #{match_id} has already been REJECTED. Duplicate rejection is prevented."
            )

        # 5. Perform Update
        now = datetime.utcnow()
        update_success = self.review_repo.update_review_decision(
            review_id=match_id,
            review_status=norm_decision,
            review_decision=norm_decision,
            reviewed_by=reviewed_by,
            review_notes=review_notes
        )

        # Sync legacy match repository if record exists there
        if legacy_match or self.match_repo.get_by_id(match_id):
            legacy_status = "Confirmed Match" if norm_decision == DECISION_CONFIRMED else ("False Positive" if norm_decision == DECISION_REJECTED else norm_decision)
            self.match_repo.update_status(match_id, legacy_status)

        if not update_success:
            # If update_one returned modified_count 0 because record was missing in review_repo,
            # but legacy update succeeded, mark success
            update_success = True

        # 6. Log Immutable Audit Entry
        audit_record = MatchReviewAudit(
            match_review_id=match_id,
            case_id=review.case_id,
            previous_status=previous_status,
            new_status=norm_decision,
            reviewer_id=reviewed_by,
            reviewer_role="admin",
            timestamp=now,
            review_notes=review_notes,
            source_type=review.source_type
        )
        self.review_repo.create_audit_record(audit_record)

        # 7. Controlled Case Status Transition & Notification Trigger
        try:
            user_obj = eff_user or {"username": reviewed_by, "role": "admin"}
            if norm_decision == DECISION_CONFIRMED:
                self.lifecycle_service.transition_case_status(
                    case_id=review.case_id,
                    requested_status="MATCH_CONFIRMED",
                    user=user_obj,
                    reason=review_notes or f"Match review #{match_id} confirmed by {reviewed_by}.",
                    related_match_review_id=str(match_id),
                )
                # Keep legacy fallback update
                self.case_repo.update_status(review.case_id, "Found")
                history_log = CaseHistory(
                    case_id=review.case_id,
                    action="Match Confirmed",
                    details=f"Biometric candidate match review #{match_id} was confirmed by {reviewed_by}. Case status updated to Found."
                )
                self.case_repo.log_history(history_log)
            elif norm_decision == DECISION_REJECTED:
                self.lifecycle_service.transition_case_status(
                    case_id=review.case_id,
                    requested_status="MATCH_REJECTED",
                    user=user_obj,
                    reason=review_notes or f"Match review #{match_id} rejected by {reviewed_by}.",
                    related_match_review_id=str(match_id),
                )
                # Auto return case back to ACTIVE_INVESTIGATION after rejection
                self.lifecycle_service.transition_case_status(
                    case_id=review.case_id,
                    requested_status="ACTIVE_INVESTIGATION",
                    user=user_obj,
                    reason="Resumed active investigation after candidate match rejection.",
                    related_match_review_id=str(match_id),
                )
        except Exception as exc:
            logger.warning("Failed to execute lifecycle transition on match review decision: %s", exc)

        # Trigger Phase 20 Email Notification (If CONFIRMED)
        if norm_decision == DECISION_CONFIRMED:
            try:
                if hasattr(self, "notification_service") and self.notification_service:
                    self.notification_service.process_match_confirmation_notification(
                        match_review_id=match_id,
                        case_id=review.case_id,
                        current_user=eff_user
                    )
            except Exception as notif_exc:
                logger.warning("Failed to process notification for match review #%s: %s", match_id, notif_exc)

        return True

    def get_audit_trail(
        self,
        review_id: int,
        current_user: Optional[dict] = None,
        user: Optional[dict] = None,
    ) -> List[MatchReviewAudit]:
        """
        Returns full audit trail history for a review record.
        Strictly enforces Admin authorization.
        """
        eff_user = current_user if current_user is not None else user
        if eff_user is not None:
            authorize_review_match(eff_user)
        return self.review_repo.get_review_history(review_id)
